MusicLibraryApp/MusicLibraryApp/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicLibraryApp.Models
{
    public class Album
    {
        public int albumID { get; set; }
        public String albumTitle { get; set; }
        public DateTime releasedYear { get; set; }
    }
}

MusicLibraryApp/MusicLibraryApp/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicLibraryApp.Models
{
    public class Artist
    {
        public int artistID { get; set; }
        public String artistName { get; set; }
        public String artistAge { get; set; }
        public int artistRank { get; set; }

    }
}

MusicLibraryApp/MusicLibraryApp/Models/MusicLibrary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace MusicLibraryApp.Models
{
    public class MusicLibrary
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public string ReleaseDate { get; set; }
        public string Genre { get; set; }
        public int AlbumSize { get; set; }
    }

    public class MusicLibraryDBContext : DbContext
    {
        public DbSet<MusicLibrary> MusicLibraries { get; set; }
    }
}

MusicLibraryApp/MusicLibraryApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicLibraryApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MusicLibraryApp/MusicLibraryApp/Controllers/MusicLibrariesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MusicLibraryApp.Models;

namespace MusicLibraryApp.Controllers
{
    public class MusicLibrariesController : Controller
    {
        private MusicLibraryDBContext db = new MusicLibraryDBContext();

        // GET: MusicLibraries
        public ActionResult Index()
        {
            return View(db.MusicLibraries.ToList());
        }

        // GET: MusicLibraries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicLibrary musicLibrary = db.MusicLibraries.Find(id);
            if (musicLibrary == null)
            {
                return HttpNotFound();
            }
            return View(musicLibrary);
        }

        // GET: MusicLibraries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MusicLibraries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public String Create(MusicLibrary musicLibrary)
        {
            if (ModelState.IsValid)
            {
                db.MusicLibraries.Add(musicLibrary);
                db.SaveChanges();
                return "success";
            }

            return null;
        }

        // GET: MusicLibraries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicLibrary musicLibrary = db.MusicLibraries.Find(id);
            if (musicLibrary == null)
            {
                return HttpNotFound();
            }
            return View(musicLibrary);
        }

        // POST: MusicLibraries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Artist,ReleaseDate,Genre,AlbumSize")] MusicLibrary musicLibrary)
        {
            if (ModelState.IsValid)
            {
                db.Entry(musicLibrary).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(musicLibrary);
        }

        // GET: MusicLibraries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicLibrary musicLibrary = db.MusicLibraries.Find(id);
            if (musicLibrary == null)
            {
                return HttpNotFound();
            }
            return View(musicLibrary);
        }

        // POST: MusicLibraries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MusicLibrary musicLibrary = db.MusicLibraries.Find(id);
            db.MusicLibraries.Remove(musicLibrary);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public JsonResult FillIndex()
        {
            return Json(db.MusicLibraries.ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

MusicLibraryApp/MusicLibraryApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MusicLibraryApp/MusicLibraryApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MusicLibraryApp/MusicLibraryApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MusicLibraryApp/MusicLibraryApp/Views/MusicLibraries/Create.cshtml
@model MusicLibraryApp.Models.MusicLibrary

@{
    ViewBag.Title = "Add Music Library";
}

<h2>Add New Music Library</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="span12">
        <fieldset>
            <legend>Add Music Library</legend>
            <div class="control-group">
                <label class="control-label">Title: </label>
                <input name="title_input" id="title_input" type="text" data-bind="value: Title" placeholder="Title" class="input-medium" />
            </div>

            <div class="control-group">
                <label class="control-label">Artist: </label>
                <input name="artist_input" id="artist_input" type="text" data-bind="value: Artist" placeholder="Artist" class="input-medium" />
            </div>

            <div class="control-group">
                <label class="control-label">Release Date: </label>
                <input name="release_date_input" id="release_date_input" type="text" data-bind="value: ReleaseDate" placeholder="Release Date" class="input-medium" />
            </div>

            <div class="control-group">
                <label class="control-label">Genre: </label>
                <input name="genre_input" id="genre_input" type="text" data-bind="value: Genre" placeholder="Genre" class="input-medium" />
            </div>

            <div class="control-group">
                <label class="control-label">Album Size: </label>
                <input name="album_size_input" id="album_size_input" type="text" data-bind="value: AlbumSize" placeholder="AlbumSize" class="input-medium" />
            </div>

            <div class="control-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="control-group">
                        <input class="btn btn-primary" type="button" value="Save" data-bind="click: btnCreateLibrary" />
                        <a class="btn btn-primary" href="@Url.Action("Cancel")">Cancel</a>
                    </div>
                </div>
            </div>

        </fieldset>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/ViewModel/CreateVM.js")
}

MusicLibraryApp/MusicLibraryApp/Views/MusicLibraries/Delete.cshtml
@model MusicLibraryApp.Models.MusicLibrary

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MusicLibrary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlbumSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlbumSize)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MusicLibraryApp/MusicLibraryApp/Views/MusicLibraries/Details.cshtml
@model MusicLibraryApp.Models.MusicLibrary

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MusicLibrary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlbumSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlbumSize)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MusicLibraryApp/MusicLibraryApp/Views/MusicLibraries/Edit.cshtml
@model MusicLibraryApp.Models.MusicLibrary

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MusicLibrary</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Artist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Artist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlbumSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlbumSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MusicLibraryApp/MusicLibraryApp/Views/MusicLibraries/Index.cshtml
@model IEnumerable<MusicLibraryApp.Models.MusicLibrary>

@{
    ViewBag.Title = "Music Library App";
}

<h2>Music Library List</h2>

<a class="btn btn-primary btn-large" href="@Url.Action("Create")">Create New</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AlbumSize)
            </th>
        </tr>
    </thead>

    <tbody data-bind="foreach: MusicLibraries">
        <tr>
            <td data-bind="text: Title"></td>
            <td data-bind="text: Artist"></td>
            <td data-bind="text: ReleaseDate"></td>
            <td data-bind="text: Genre"></td>
            <td data-bind="text: AlbumSize"></td>
            <td>
                <a href="#" data-bind="Edit, click: $parent.editLibrary">Edit</a> |
                <a href="#" data-bind="Details, click: $parent.detailsLibrary">Details</a> |
                <a href="#" data-bind="Delete, click: $parent.deleteLibrary">Delete</a>
            </td>
        </tr>
    </tbody>
</table>

@section Scripts {
    @Scripts.Render("~/Scripts/ViewModel/IndexVM.js")
}

MusicLibraryApp/MusicLibraryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Music Library App", "Index", "MusicLibraries", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @RenderSection("scripts", required: false)
</body>
</html>